services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel
    volumes:
      - polls_pg_data:/bitnami/postgresql/data

volumes:
  polls_pg_data:
